apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ci-test-1
  name: ci-test-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-test-1
  template:
    metadata:
      labels:
        app: ci-test-1
    spec:
      containers:
        - image: ci-test-1
          name: ci-test-1
          ports:
            - name: http
              containerPort: 8080
      imagePullSecrets:
      - name: gitlab-registry
