apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
namespace: ci-test
images:
- name: ci-test-1
  newName: chenu2/ci-test
  newTag: 89d7c25ec8032ed16fc09335a4c99e19bd7a4d98
