apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
namespace: ci-test
images:
- name: ci-test-1
  newName: registry.mooplab.com/test-group/ci-test
  newTag: 2449fd0f
