apiVersion: v1
kind: Service
metadata:
  labels:
    app: ci-test-1
  name: ci-test-1
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: ci-test-1
  type: LoadBalancer
